name: ESLint Frontend

on:
  push:
    branches: [main]

jobs:
  super-linter:
    name: ESLint Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up node 
        uses: actions/setup-node@v1

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: ESLint Frontend
        working-directory: ./frontend
        run: npx eslint .