name: Lint Code Base

on:
  push:
    branches: [main]

jobs:
  super-linter:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up node 
        uses: actions/setup-node@v1
      
      - name: Install dependencies
        working-directory: ./backend
        run: npm install

      - name: Test Backend
        working-directory: ./backend
        run: npx eslint .

      # - name: Install dependencies
      #   working-directory: ./frontend
      #   run: npm install

      # - name: Test Frontend
      #   working-directory: ./frontend
      #   run: npx eslint .