name: Test Frontend

on:
  push:
    branches: [main]

jobs:
  test-with-jest:
    name: Test Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
  
      - name: Set up node 
        uses: actions/setup-node@v1

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Test Frontend
        working-directory: ./frontend
        run: npm run test