name: Test Backend

on:
  push:
    branches: [main]

jobs:
  test-with-jest:
    name: Test Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
  
      - name: Set up node 
        uses: actions/setup-node@v1
      
      - name: Install dependencies
        working-directory: ./backend
        run: npm install

      - name: Test Backend
        working-directory: ./backend
        run: npm run test