name: Test App

on:
  push:
    branches: [main]

jobs:
  test-with-jest:
    name: Test App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
  
      - name: Set up node 
        uses: actions/setup-node@v1

      - name: Install dependencies
        working-directory: ./app
        run: npm install

      - name: Run ESLint
        working-directory: ./app
        run: npm run test